CREATE OR REPLACE FUNCTION echo(msg TEXT) RETURNS TEXT AS $$ BEGIN RETURN msg; END; $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION echoProc (msg TEXT, OUT res TEXT) AS $$ BEGIN res:=msg; END; $$ LANGUAGE plpgsql;
